name: test-workflow
on: [push]
jobs:
  checkout-master-setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:   
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        
